export const REQUEST_USER = 'REQUEST_USER';
export const IS_PUBLIC_KEY = 'IS_PUBLIC_KEY';
export const IS_VERIFYING = 'IS_VERIFYING';
export const COOKIE_REFRESH_TOKEN = 'REFRESH_TOKEN';
export const PREFIX_TOKEN_IAT = 'TOKEN_IAT_AVAILABLE';
export const USER_VERIFY_CODE = 'USER_VERIFY_CODE';
